### ISSUE TITLE
Accumulation allure-results

### ISSUE THREAD

**Issue by cerebellum13** [Noksa/Allure.NUnit#25]
I run tests through Visual Studio more than once, but each test suite is separate. In this regard, the results of the allure are deleted and new ones begin to be created. But I want to keep the old ones, but there is no opportunity to accumulate these results. Is there any way to fix this?

 - NUnit: 3.12.0
 - Allure: 2.6.2

**Comment by Noksa** [comment]
@cerebellum13 
For local history of test runs, you can use the setting in the config `allure.allowLocalHistoryTrend`

**Comment by cerebellum13** [comment]
@Noksa 
But, it doesn't work for me. Still continues to delete.

**Comment by Noksa** [comment]
@cerebellum13 
My mistake - i mixed up the history with the trend.
Currently, the local launches history is not implemented and is not planned, because the CI server does this.

**Comment by cerebellum13** [comment]
Very sorry of course, have to make crutches = (
