### ISSUE TITLE
??? in Allure reports

### ISSUE THREAD

**Issue by cerebellum13** [Noksa/Allure.NUnit#26]
I use SpecFlow and Gherkin scenarios with NUnit and Allure for reporting. In Allure reports (after build and deploy of allure reports) in reports I have ??? instead of russian equivalents in Parameters table.

![image](https://user-images.githubusercontent.com/19388630/63259682-bbe17800-c287-11e9-8f20-bdb5ada953b5.png) 

How I can fix this issue?
**Versions**
 - NUnit: 3.12.1
 - Noksa.NUnit.Allure: 2.6.2

**Comment by iamfreid** [comment]
Вероятно проблема в этом:

https://github.com/Noksa/Allure.NUnit/blob/488af40fd41f06591420d0e1f8da56afbf1058be/AllureSpecFlow/AllureTestTracerWrapper.cs#L90

https://github.com/Noksa/Allure.NUnit/blob/488af40fd41f06591420d0e1f8da56afbf1058be/AllureSpecFlow/AllureTestTracerWrapper.cs#L147

**Comment by Noksa** [comment]
@cerebellum13 
This is a bug.
Thanks for reporting.
Will be fixed soon.

**Comment by Noksa** [comment]
Fixed in 1.1.3 https://www.nuget.org/packages/Noksa.NUnit.SpecFlow3/1.1.3

**Comment by cerebellum13** [comment]
Thanks!
