### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gremlinica** [Noksa/Allure.NUnit#34]
Hi,
your solution is really cool and we'd like to use it for internal testing. Could you tell us what the license is for commercial use?

**Comment by Noksa** [comment]
@gremlinica  Hey.
It is just an adapter with some improvements.
At the moment, and I think it will always be distributed under MIT license.

**Comment by gremlinica** [comment]
@Noksa Thanks a lot for the prompt reply. Cheers!
