### ISSUE TITLE
Unable to write to the Allurereport with [AllureStep]

### ISSUE THREAD

**Issue by Rupasri33** [Noksa/Allure.NUnit#42]
**Describe the bug**
I'm using a library project that uses NOKSA.Allure 3.10 that has methods with [AllureStep] and importing this library in to Tests project and when I initiate the test ,nothing is logged in to report 
I have Allureconfig.json in the working directory and set the properties set to copy to output folder

I see the error below in event viewer with dump file (attached) 
do you have any leads to the error ?

**[dumpFile.txt](https://github.com/Noksa/Allure.NUnit/files/4236987/dumpFile.txt)**

Application: Noksa.Allure.StepInjector.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at Noksa.Allure.StepInjector.Injection.Injector..ctor(System.Collections.Generic.IEnumerable`1<System.String>)
   at Noksa.Allure.StepInjector.Program.Main(System.String[])

**Versions**
-Net Framework :4.7.2
 - NUnit: ...3.12
 - Allure: ...
-Noksa.NUnit.Allure : 3.1.0
-Noksa.Allure.StepInjector :2.0.1

Any help is greatly appreciated.

**Comment by Noksa** [comment]
Hello.
Can you please upload a project, where I can reproduce error?
Thanks

**Comment by Rupasri33** [comment]
I could figure out the issue. The issue is with using the Latest version of
 Newtonsoft.json package 12.0.3 and Mono.Cecil version 0.11.2  with Noksa.Nunit.Allure 3.1.0

I installed Noksa.Nunit.Allure 3.1.0 but later updated to the latest versions of newtonsoft.json and Mono.Cecil version that caused the issue . The warning message is also noted in build log with 532462766 exit code for Noksa.allure.StepInjector. 
C# compiler throws this error

**Comment by Noksa** [comment]
@Rupasri33 
This is a bug. I will see what has changed in the new version of mono cecil.

**Comment by Rupasri33** [comment]
Thank you!

**Comment by Noksa** [comment]
Released in new beta
