### ISSUE TITLE
Question about Console Output catching.

### ISSUE THREAD

**Issue by dklementyev** [Noksa/Allure.NUnit#43]
Hello! 
It's not like a bug. It sounds more like question. Is it possible to add Console output of .net core application into Allure Report? 

I tried like catch output in BeforeStep and add Attachment in afterStep, but attachments not added to step, it added after all steps.
Add ScreenShot as an example.

![image](https://user-images.githubusercontent.com/18246987/75570327-fbbfbe00-5a67-11ea-8098-9d4b719e98ad.png)

So, I use:
Specflow 3
NUnit Adapter
Noksa.NUnit.SpecFlow3

**Comment by Noksa** [comment]
@dklementyev Hello!
At the moment, the call of any AfterStep occurs after the completion of the step.
I will see what can be done with this.

**Comment by dklementyev** [comment]
@Noksa Hi. 
Thanks a lot! Please keep me updated in case of this!

**Comment by Noksa** [comment]
@dklementyev 
Try a new beta please: https://www.nuget.org/packages/Noksa.NUnit.SpecFlow3/1.2.0-beta1
Now you can add your logic to the step update in methods with the AfterStep attribute

**Comment by dklementyev** [comment]
@Noksa 
Thanks! Now it works for AddAttachment method from AllureLifeCycle.Instance.
