### ISSUE TITLE
Step result doesn't update with method return value

### ISSUE THREAD

**Issue by Rupasri33** [Noksa/Allure.NUnit#44]
**Describe the bug**
I added the [Step] annotation on a method that maps to a step in the test case and the method returns Boolean value. When the method returns false, the step result shows as Pass(green) even though the method returns false unless the method throws exception to report as false.
**To Reproduce**
[AllureStep("RegistrationConfirmationPage")]
        public bool VerifyRegistration()
        {
            logger.Info("Verify registration");
            if (condition==true)
            {
             
                return true;
            }
            else
            {
               
                return false;
            }
**Expected behavior**
based on return type of method, Is there a way to report the step result .If this is not supported, I think its good to have
**Screenshots**

**Versions**
 - NUnit: ...3.10.1
 - Allure: ...3.1.0.

**Comment by Noksa** [comment]
@Rupasri33 Hello!
I think this is a bad idea.
Not always returning false from a method indicates that it worked incorrectly.
It is possible that this is the correct behavior, and in this case that the step should be green.
Just for this reason, only throwing an exception works like a “step failed”.
Btw classic method "RunStep" and all his overloads are work like this.

If you want to mark step as failed, you can use inside it a substep:
`AllureLifecycle.Instance.Verify.Fail`.

**Comment by Rupasri33** [comment]
Thanks for your response
