### ISSUE TITLE
Breaking change in SpecFlow 3.3.57

### ISSUE THREAD

**Issue by DanielVuurboom** [Noksa/Allure.NUnit#49]
**Describe the bug**
When upgrading SpecFlow to version 3.3.57 the constructor for ScenariInfo is changes from:
public ScenarioInfo(string title, string description, params string[] tags)
to:
public ScenarioInfo(string title, string description, string[] tags, IOrderedDictionary arguments)

This results in a failure to create the
private static readonly ScenarioInfo EmptyScenarioInfo = new ScenarioInfo(string.Empty, string.Empty);
in Allure.NUnit/AllureSpecFlow/PluginHelper.cs

**To Reproduce**
Run any scenario with this package combination:
```
    <PackageReference Include="Noksa.NUnit.Allure" Version="3.1.0" />
    <PackageReference Include="Noksa.NUnit.SpecFlow3" Version="1.1.5" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0">
    <PackageReference Include="SpecFlow" Version="3.3.57" />
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.3.57" />
    <PackageReference Include="SpecFlow.NUnit" Version="3.3.57" />
```

**Comment by Noksa** [comment]
You can find new packages on the nuget.org
